### ISSUE TITLE
from_slice behavior

### ISSUE THREAD

**Issue by ekmett** [horasal/bitvector_simd#2]
it seems to me that the `from_slice` behavior is inconsistent in the presence of repeated indices.

It looks like it assumes that setting from a slice will have at least as many elements as there are in the slice, but if there are repeats then the slice will be set to a larger capacity than is required.

If this tracked nbits separately from the array length of the backing store, then you could still guess at the capacity requirement of the slice by dividing that slice size by 512 (rounded up) and using it as a starting guess at how many BitContainers to put in the backing array, update nbits as you scan through the slice to the highest watermark actually observed, and then trim the backing vec's size back down to fit the data you have.

**Comment by horasal** [comment]
Thanks for your feedback! 

I agree with you that current [`from_slice` imprementation](https://github.com/horasal/bitvector_simd/blob/main/src/lib.rs#L256) is inconsistent. Slices with repeated indices may cause it use more memory than expected.

We have several options to solve this:

1. Trace the max index and add a `shirk_to` before return.
2. Change initial length to `slice.max()` to avoid any allocation.
3. Change initial length to `0` make sure no memory is wasted.

I did some benches on these solutions, and it shows that the first one has better performance over others.
I'll make a patch later with the first solution and thanks for your feedback again!

```
from_slice, small set, capacity=slice.len()                                                                             
                        time:   [6.7193 us 6.7212 us 6.7232 us]
                        change: [+0.6780% +0.9091% +1.1639%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 21 outliers among 100 measurements (21.00%)
  3 (3.00%) low severe
  5 (5.00%) low mild
  5 (5.00%) high mild
  8 (8.00%) high severe

from_slice, small set, capacity=slice.max()                                                                             
                        time:   [6.8733 us 6.8753 us 6.8776 us]
                        change: [-0.2958% -0.1312% +0.0648%] (p = 0.18 > 0.05)
                        No change in performance detected.
Found 11 outliers among 100 measurements (11.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  7 (7.00%) high severe

from_slice, small set, capacity=0                                                                             
                        time:   [6.8792 us 6.8811 us 6.8833 us]
                        change: [-0.3338% -0.0785% +0.1143%] (p = 0.56 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

from_slice, large set, capacity=slice.len()                                                                            
                        time:   [121.72 us 121.84 us 121.95 us]
                        change: [+0.3143% +0.4387% +0.5645%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

from_slice, large set, capacity=slice.max()                                                                            
                        time:   [123.99 us 124.12 us 124.24 us]
                        change: [-0.4949% -0.3700% -0.2379%] (p = 0.00 < 0.05)
                        Change within noise threshold.

from_slice, large set, capacity=0                                                                            
                        time:   [124.02 us 124.15 us 124.28 us]
                        change: [-0.4067% -0.2901% -0.1640%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
```
